version: '2'
services:
  web:
    build: .
    image: web
    ports:
      - "8080:5000"
    volumes:
      - .:/ccl
    entrypoint:
      - python
      - ccl.py
#    depends_on:
#      - db
#  db:
#    image: redis
